### ISSUE TITLE
Would love to make use of this but unable to install

### ISSUE THREAD

**Issue by CalebDueck** [dotMorten/StreamDeckCalendar#1]
Any specific details on how to install this? Tried running both powershell items but didn't work.

**Comment by dotMorten** [comment]
Sorry I've stopped maintenance on this because Microsoft has replaced their Mail & Calendar app with the new Outlook app that doesn't use the Windows calendar APIs that this plugin was relying on.

**Comment by CalebDueck** [comment]
Fair enough, thanks so much for the quick response. Looks like it was an
awesome tool.
